services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Maps2\:
    resource: '../Classes/*'

  JWeiland\Maps2\Configuration\ExtConf:
    public: false

  JWeiland\Maps2\Helper\MapHelper:
    public: false
